# Generated by Django 5.1.5 on 2025-01-26 17:07

import Music_player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_icons', models.ImageField(upload_to='')),
                ('music_title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='', validators=[Music_player.models.validate_audio_file])),
                ('artist_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList_or_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayList_or_Album_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
    ]
