# Generated by Django 5.1.5 on 2025-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album_name',
            new_name='albumName_or_playlistName',
        ),
        migrations.RenameField(
            model_name='playlist_or_album',
            old_name='PlayList_or_Album_name',
            new_name='PlayList_or_AlbumName',
        ),
        migrations.AddField(
            model_name='playlist_or_album',
            name='songs',
            field=models.ManyToManyField(related_name='playlists_or_albums', to='Music_player.music'),
        ),
    ]
