# Generated by Django 5.1.5 on 2025-01-26 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_player', '0003_music_created_at_playlist_or_album_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_or_album',
            name='play_list_cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
